const $=s=>document.querySelector(s);let prefs,overview,archiveNext=null,readerState,dirty=false,generating=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const stamp=d=>new Intl.DateTimeFormat('es-MX',{dateStyle:'short',timeStyle:'short',timeZone:'America/Mexico_City'}).format(new Date(d));
const identity=m=>`${m.day}/${m.revision||'daily'}`;const img=(m,p=1)=>`/panel/api/image/${identity(m)}/${p}`;
function notice(s){$('#notice').textContent=s;}
function showLogin(){for(const d of document.querySelectorAll('dialog[open]'))d.close();$('#login').hidden=false;$('#app').hidden=true;}
async function api(path,options={}){const r=await fetch('/panel/api'+path,{...options,headers:{'Content-Type':'application/json','X-Panel-Request':'1',...options.headers}});let value;try{value=await r.json();}catch{value={error:'No se pudo completar la solicitud.'};}if(r.status===401){showLogin();throw Error(value.error);}if(!r.ok)throw Error(value.error||'No se pudo completar la solicitud.');return value;}
function setTab(name){document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==name);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('selected',x.dataset.tab===name));if(name==='archive')loadArchive();}
async function loadApp(){overview=await api('/overview');$('#login').hidden=true;$('#app').hidden=false;await loadToday();prefs=await api('/preferences');renderSources();}
function same(a,b){return a&&b&&a.day===b.day&&(a.revision||'daily')===(b.revision||'daily');}
async function loadToday(){const m=overview.latest;$('#today-date').textContent=date(overview.today).toUpperCase();
 if(!m){$('#today-content').innerHTML='<div class="empty"><h2>Tu primera edición está por llegar.</h2><p>Revisa tus fuentes antes de generar el periódico.</p><button id="generate">Preparar edición</button></div>';$('#generate').onclick=openGenerate;return;}
 const {edition}=await api('/edition/'+identity(m));const e=edition.editorial;const received=same(overview.receipt,m)?overview.receipt:same(overview.alarm,m)?overview.alarm:null;
 const opened=received?.stage==='opened';const status=opened?'Abierto en tu Kindle':received?'Descargado por el Kindle':'Listo en la nube';
 const run=overview.run;let extra='';if(m.day!==overview.today)extra='Estás viendo la última edición disponible. ';if(run?.status==='failed')extra+='La generación de hoy falló. Se conserva la anterior.';if(run?.status==='started')extra+='La edición de hoy está en preparación.';
 $('#today-content').innerHTML=`<div class="hero"><div class="hero-cover"><img src="${img(m)}" alt="Portada de la edición del ${esc(date(m.day))}"></div><div class="hero-details"><span class="badge ${opened?'':'warn'}">${status}</span><h2>${esc(e.headline)}</h2><p class="muted">${esc(e.introduction)}</p><div class="hero-actions"><button id="read-current">Leer edición →</button><button id="generate" class="secondary" ${generating?'disabled':''}>${generating?'Preparando…':'Generar otra edición'}</button></div><div class="delivery"><p>${esc(date(m.day))} · ${m.pages.length} páginas${m.revision?' · Edición de prueba':''}</p><p class="muted">${opened?'Apertura confirmada':received?'Descarga confirmada':'Sin confirmación del dispositivo'}${received?' · '+esc(stamp(received.at)):''}</p>${extra?`<p class="muted">${esc(extra)}</p>`:''}</div></div></div>`;
 $('#read-current').onclick=()=>openEdition(m);$('#generate').onclick=openGenerate;
}
async function loadArchive(append=false){try{if(!append)$('#archive-grid').innerHTML='<p class="muted">Buscando ediciones…</p>';const data=await api('/archive?offset='+(append?archiveNext:0));if(!append)$('#archive-grid').replaceChildren();for(const e of data.editions){const card=document.createElement('article');card.className='edition-card';card.innerHTML=`<button><div class="thumb"><img loading="lazy" src="${img(e)}" alt="Portada del ${esc(date(e.day))}"></div><div class="card-copy"><p class="eyebrow">${esc(date(e.day))}</p><h3>${esc(e.headline)}</h3><p class="summary muted">${esc(e.summary)}</p><p class="small muted">${e.pages} páginas · ${e.revision?'Prueba '+esc(stamp(e.generated_at)):'Edición diaria'}</p></div></button>`;card.querySelector('button').onclick=()=>openEdition(e);$('#archive-grid').append(card);}if(!$('#archive-grid').children.length)$('#archive-grid').innerHTML='<p>Aún no hay ediciones publicadas.</p>';archiveNext=data.next;$('#load-more').hidden=archiveNext===null;}catch(e){notice(e.message);}}
async function openEdition(m){try{const data=await api('/edition/'+identity(m));readerState={...m,page:1,pages:data.manifest.pages.length};$('#reader-title').textContent=date(m.day);$('#reader-meta').textContent=`${readerState.pages} páginas · ${m.revision?'Edición de prueba':'Edición diaria'}`;const e=data.edition;$('#reader-summary').innerHTML=`<p class="eyebrow">EN ESTA EDICIÓN</p><h3>${esc(e.editorial.headline)}</h3><p>${esc(e.editorial.introduction)}</p>${e.editorial.articles.map(a=>`<h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><p class="small muted">${esc(a.why)}</p><ul>${a.sources.filter(u=>/^https:\/\//.test(u)).map(u=>`<li><a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(new URL(u).hostname)}</a></li>`).join('')}</ul>`).join('')}<h3>Tu agenda</h3>${e.agenda.length?e.agenda.map(a=>`<p><strong>${esc(a.time)}</strong> ${esc(a.title)}</p>`).join(''):'<p>Sin eventos en esta edición.</p>'}`;renderPage();$('#reader').showModal();}catch(e){notice(e.message);}}
function renderPage(){$('#reader-image').src=img(readerState,readerState.page);$('#reader-image').alt=`Página ${readerState.page} del periódico`;$('#page-count').textContent=`${readerState.page} / ${readerState.pages}`;$('#prev-page').disabled=readerState.page===1;$('#next-page').disabled=readerState.page===readerState.pages;}
function markDirty(){dirty=true;$('#save-state').textContent='Tienes cambios sin guardar.';}
function renderSources(){const box=$('#source-list');box.replaceChildren();$('#source-count').textContent=`${prefs.senders.filter(x=>x.enabled).length} activas / ${prefs.senders.length}`;prefs.senders.forEach((s,i)=>{const row=document.createElement('div');row.className='source-row';row.innerHTML=`<div><p class="email">${esc(s.email)}</p><p class="status">${s.enabled?'Activa para la próxima edición':'En pausa'}</p></div><div class="source-actions"><button class="secondary toggle" aria-label="${s.enabled?'Pausar':'Activar'} ${esc(s.email)}">${s.enabled?'Pausar':'Activar'}</button><button class="quiet remove" aria-label="Quitar ${esc(s.email)}">Quitar</button></div>`;row.querySelector('.toggle').onclick=()=>{s.enabled=!s.enabled;markDirty();renderSources();};row.querySelector('.remove').onclick=()=>{prefs.senders.splice(i,1);markDirty();renderSources();};box.append(row);});$('#lookback').value=prefs.lookbackDays;$('#max-messages').value=prefs.maxMessages;}
$('#add-source').onsubmit=e=>{e.preventDefault();const email=$('#sender').value.trim().toLowerCase();if(prefs.senders.some(s=>s.email===email))return notice('Ese correo ya está en tu lista.');if(prefs.senders.length>=20)return notice('Puedes guardar hasta 20 fuentes.');prefs.senders.push({email,enabled:true});$('#sender').value='';markDirty();renderSources();notice('');};
$('#lookback').onchange=()=>{prefs.lookbackDays=Number($('#lookback').value);markDirty();};$('#max-messages').oninput=()=>{prefs.maxMessages=Number($('#max-messages').value);markDirty();};
$('#save-sources').onclick=async()=>{const button=$('#save-sources');button.disabled=true;try{const {version,...preferences}=prefs;prefs=await api('/preferences',{method:'PUT',body:JSON.stringify({version,preferences})});dirty=false;renderSources();$('#save-state').textContent='Guardado. Se aplicará a la próxima edición.';notice('');}catch(e){notice(e.message);}finally{button.disabled=false;}};
function openGenerate(){if(generating)return;if(dirty)return notice('Guarda tus fuentes antes de generar otra edición.');$('#generate-dialog').showModal();}
$('#confirm-generate').onclick=async()=>{$('#generate-dialog').close();generating=true;$('#generate').disabled=true;$('#generate').textContent='Preparando…';notice('Preparando una edición nueva. Puede tardar varios minutos; no hace falta volver a pulsar.');try{await api('/generate',{method:'POST',body:JSON.stringify({revision:String(Date.now())})});notice('Edición publicada. El Kindle la recibirá en su próxima consulta.');overview=await api('/overview');await loadToday();}catch(e){notice(e.message+' Si se interrumpió la conexión, actualiza el estado antes de generar otra vez.');}finally{generating=false;if($('#generate')){$('#generate').disabled=false;$('#generate').textContent='Generar otra edición';}}};
$('#login-form').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;try{await api('/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';$('#login-error').textContent='';await loadApp();}catch(e){$('#login-error').textContent=e.message;}finally{b.disabled=false;}};
$('#logout').onclick=async()=>{try{await api('/logout',{method:'POST',body:'{}'});showLogin();}catch(e){notice(e.message);}};
$('#refresh').onclick=async()=>{try{overview=await api('/overview');await loadToday();notice('Estado actualizado.');}catch(e){notice(e.message);}};
$('#load-more').onclick=()=>loadArchive(true);$('#close-reader').onclick=()=>$('#reader').close();$('#cancel-generate').onclick=()=>$('#generate-dialog').close();$('#prev-page').onclick=()=>{readerState.page--;renderPage();};$('#next-page').onclick=()=>{readerState.page++;renderPage();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));window.addEventListener('beforeunload',e=>{if(dirty||generating){e.preventDefault();e.returnValue='';}});
loadApp().catch(e=>{if(!$('#app').hidden)notice(e.message);});
