import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomBytes} from 'node:crypto';
import {Store} from '../src/store.js';import {createApp} from '../src/app.js';import {readPreferences,savePreferences} from '../src/preferences.js';
const preferences={senders:[{email:'news@example.com',enabled:true},{email:'paused@example.com',enabled:false}],lookbackDays:3,maxMessages:12};
test('private panel auth, CSRF, durable sources, conflict, archive authorization and logout',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'panel-test-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const store=new Store(root);
 const saved={...process.env};process.env.ENCRYPTION_KEY=randomBytes(32).toString('base64');process.env.ADMIN_TOKEN='a'.repeat(64);process.env.DEVICE_TOKEN='d'.repeat(64);process.env.NEWSLETTER_SENDERS='seed@example.com';process.env.PUBLIC_URL='http://127.0.0.1:4319';
 const server=createApp(store).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>{server.close();for(const k of ['ENCRYPTION_KEY','ADMIN_TOKEN','DEVICE_TOKEN','NEWSLETTER_SENDERS','PUBLIC_URL']){if(saved[k]===undefined)delete process.env[k];else process.env[k]=saved[k];}});const base='http://127.0.0.1:'+server.address().port;
 const call=(p,method='GET',body,headers={})=>fetch(base+p,{method,headers:{'content-type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});
 for(const p of ['/panel/api/overview','/panel/api/archive','/panel/api/preferences','/panel/api/image/2026-09-29/daily/1'])assert.equal((await call(p)).status,401);
 assert.equal((await call('/panel/api/preferences','GET',null,{authorization:'Bearer '+process.env.DEVICE_TOKEN})).status,401);
 const secret='panel-password-for-test-1234';assert.equal((await call('/admin/panel-password','POST',{password:secret})).status,401);
 assert.equal((await call('/admin/panel-password','POST',{password:secret},{authorization:'Bearer '+process.env.ADMIN_TOKEN})).status,200);
 assert.equal((await call('/panel/api/login','POST',{password:secret})).status,403);
 const origin={origin:process.env.PUBLIC_URL,'x-panel-request':'1'};
 assert.equal((await call('/panel/api/login','POST',{password:'wrong'},origin)).status,401);
 const login=await call('/panel/api/login','POST',{password:secret},origin);assert.equal(login.status,200);const raw=login.headers.get('set-cookie');assert.match(raw,/HttpOnly/i);assert.match(raw,/SameSite=Strict/i);const cookie=raw.split(';')[0];const headers={...origin,cookie};
 const first=await(await call('/panel/api/preferences','GET',null,headers)).json();assert.equal(first.senders[0].email,'seed@example.com');
 assert.equal((await call('/panel/api/preferences','PUT',{version:0,preferences},{cookie})).status,403);
 assert.equal((await call('/panel/api/preferences','PUT',{version:0,preferences},headers)).status,200);
 assert.equal((await call('/panel/api/preferences','PUT',{version:0,preferences},headers)).status,409);
 assert.deepEqual((await readPreferences(new Store(root))).senders,preferences.senders);
 const invalid={...preferences,senders:[{email:'{ from:someone }',enabled:true}]};assert.equal((await call('/panel/api/preferences','PUT',{version:1,preferences:invalid},headers)).status,400);
 assert.equal((await call('/panel/api/preferences','PUT',{version:1,preferences:{...preferences,senders:preferences.senders.map(s=>({...s,enabled:false}))}},headers)).status,400);
 assert.equal((await call('/panel/api/archive','GET',null,headers)).status,200);
 assert.equal((await call('/panel/api/image/2026-09-29/daily/1','GET',null,headers)).status,404);
 const logout=await call('/panel/api/logout','POST',{},headers);assert.match(logout.headers.get('set-cookie'),/Expires=Thu, 01 Jan 1970/i);
 await call('/admin/panel-password','POST',{password:'another-long-test-password'},{authorization:'Bearer '+process.env.ADMIN_TOKEN});assert.equal((await call('/panel/api/preferences','GET',null,headers)).status,401);
});
test('only one concurrent settings writer commits the same version',async t=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'panel-race-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const store=new Store(root);const results=await Promise.allSettled([savePreferences(store,preferences,0),savePreferences(store,preferences,0)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await readPreferences(store)).version,1);});
